spring.application.name=ride-wise-cab-sharing
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/ridewise?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=manav@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:run.sql
spring.jpa.defer-datasource-initialization=true